### ISSUE TITLE
Empty player list with Arch Linux

### ISSUE THREAD

**Issue by goshhhy** [zbanks/CrewLink#1]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [X] I am using the Steam version of Among Us
3. [X] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [X] I have checked everyone in my lobby is on the same CrewLink server
5. [X] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [X] I have checked that the CrewLink server I'm using is up to date
7. [X] I have a screenshot of any errors
8. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
CrewLink connects to the server, but the player list does not appear, and other players cannot hear me.

**To Reproduce**
Steps to reproduce the behaviour:
Run CrewLink (either the release or manually built) on Arch Linux, and connect to a CrewLink server. 

**Expected behaviour**
CrewLink connects the server, the player list appears, and I am able to hear and speak to other players.

**Screenshots**
![the screen that appears after connecting to the server](https://user-images.githubusercontent.com/37872995/102702162-15efa600-420c-11eb-93a1-31a80b1e14f0.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 1.1.6?

**Additional context**
I am running a server myself, and can confirm that the connection occurs, and all players are on that server. Other players see me in their list, but cannot hear me.

**Comment by zbanks** [comment]
Sorry for making you fill out the template - that was the default from the main fork!

What version of Among Us are you running? And where does it come from? Right now only 2020.12.9 from Steam is supported. 
The `sha256sum` of your `GameAssembly.dll` should match mine here:

```
$ sha256sum ~/.local/share/Steam/steamapps/common/Among\ Us/GameAssembly.dll 
0b010bd3195d39c089dc018d834b2ebd26ba67d2f49c4ebea608a804fc0975b7  /home/zbanks/.local/share/Steam/steamapps/common/Among Us/GameAssembly.dll
```

Other versions that _are_ supported by the main CrewLink might work if you change [the `version` variable in `hook.ts](https://github.com/zbanks/CrewLink/blob/master/src/main/hook.ts#L33).
I know the offsets for the itch.io verison haven't been figured out yet. [This project](https://github.com/denverquane/amonguscapture/blob/master/Offsets.json) has the best list of offsets that I've seen -- if your hash isn't in there, I don't think it'll be supported.

Also it could be a ptrace permissions issue? If that's the case, it'd spam the console with permission errors, and would be fixed by running `echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope` (allowing processes to read/write the memory of other processes!)

**Comment by goshhhy** [comment]
i am using the same version as you, and the ptrace permission is set as you said:

```
sanae@akarui ~> sha256sum /usr/games/steamapps/common/Among\ Us/GameAssembly.dll
0b010bd3195d39c089dc018d834b2ebd26ba67d2f49c4ebea608a804fc0975b7  /usr/games/steamapps/common/Among Us/GameAssembly.dll
sanae@akarui ~> cat /proc/sys/kernel/yama/ptrace_scope
0
sanae@akarui ~> 
```

it does not return permission errors, however i do see the following message repeated many times:
```
  error: process_vm_readv returned -1 instead of 4 (Function not implemented) address=0x4d67f54 
```
where the address is different on each line.

**Comment by zbanks** [comment]
Oh cool - that's actually enough to narrow it down.
I think this means that your kernel was built without support for the `process_vm_readv` syscall ([`CONFIG_CROSS_MEMORY_ATTACH`](https://cateee.net/lkddb/web-lkddb/CROSS_MEMORY_ATTACH.html)).

I found a few other applications where users reported similar issues with "`process_vm_readv`" and "`Function not implemented`". Kind of surprised this was a problem on Arch, I thought I had someone successfully use this on "stock" Arch. Not sure if you've done anything to manually compile your kernel?

**Comment by goshhhy** [comment]
my kernel is in fact not a stock arch kernel - i can recompile it myself with that enabled. good to know it's just my weird setup, in this instance!

**Comment by goshhhy** [comment]
so, it seems like my config wasn't the issue - CONFIG_CROSS_MEMORY_ATTACH was built into my kernel. upgrading from 5.4 to 5.10 seemed to do the trick, though, and now i *think* it's working. thanks for your assistance.
