### ISSUE TITLE
Among Us is not recognized (Manjaro Linux)

### ISSUE THREAD

**Issue by Blui42** [zbanks/CrewLink#3]
Upon launching  the AppImage, This error message appeared. (I am running the correct version)
![image](https://user-images.githubusercontent.com/61911304/103164844-a6cc1000-4810-11eb-8327-153739b2866e.png)
This is the console output.
[Log.txt](https://github.com/zbanks/CrewLink/files/5744133/Log.txt)

Just to check, I launched the AppImage again without Among us being open and got the same message.

Launch Options(without these Among us doesn't start): PROTON_NO_ESYNC=1 PROTON_USE_WINED3D=1 %command%
Proton: 4.11-13
System: Manjaro KDE 64-bit
CPU: AMD Ryzen 5
GPU: Nvidia Quadro 4000

I hope this helps :)

**Comment by Darkhogg** [comment]
I'm getting the same message, with or without Among Us open.

**Comment by alexboily-ls** [comment]
This is because offsets are bundled with the client now, see [this commit](https://github.com/ottomated/CrewLink-server/commit/ec116e0d228048cc13c003d7b714749645b10a6a) from 4 days ago. The URL does not exist anymore.

I'm on Manjaro too, currently trying to debug the code to make this run. So far I grabbed a copy of the offsets yaml file, directly loaded it in the code, and made that bit "work". But now I get an error message about my microphone not being recognized, and a bunch of error messages in the console, so I haven't found a complete working solution.

**Comment by zbanks** [comment]
This should be fixed on the [latest release, v1.2.1](https://github.com/zbanks/CrewLink/releases/tag/v1.2.1). You can re-open this issue if it is not.
